### ISSUE TITLE
Publish a prototype

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fourier-making-waves#102]
Ariel had some inquiries about Fourier: Making Waves at the recent New Faculty Workshop, and suggested that we consider publishing a prototype. 

The publication milestone is still a few months out, and it's unlikely to be completed in time for the start of the semester. However, the first two screens are in great shape, so we could consider publishing a prototype with `screens=1,2`. What do you think @kathy-phet @pixelzoom?

FYI @pixelzoom -- publishing a prototype is essentially the same as publishing a sim normally. I'll mark the sim as a "Prototype" on its admin page (but won't make it visible).

**Comment by pixelzoom** [comment]
A prototype is OK with me.  But it will affect the 1.0 schedule.  Plan on pushing all milestones out at least a week, to account for the time that I'll spend shepherding the prototype through the process, fixing issues, etc.

If you decide to proceed, let me know if there are any features that I should turn off (UI sounds, keyboard traversal,...)

**Comment by arouinfar** [comment]
@pixelzoom I wouldn't turn off sound or alt input, just hide the Wave Packet screen. Let's discuss at design meeting.

**Comment by pixelzoom** [comment]
7/15/20921 design meeting @arouinfar @kathy-phet @pixelzoom

The plan is:
* hide the Wave Packet screen
* dev-lite testing
* RC-lite testing
* publish 1.0.0 as a prototype

Start this next week, after NS 1.4 is published.

**Comment by pixelzoom** [comment]
The dev-lite test is in the QA queue (see https://github.com/phetsims/qa/issues/673) but I have not published the dev version yet. QA has other higher-priority testing, and it doesn't make sense to have a dev version become stale. @KatieWoe is going to notify me when they are ready to begin working on https://github.com/phetsims/qa/issues/673.

**Comment by pixelzoom** [comment]
@kathy-phet and I discussed this on Slack a bit on Wednesday 7/21/21.  She asked me to publish a dev version for QA testing, and I couldn't do that.  We weren't ready to start testing as planned (early in the week), and I felt like I should proceed with core development of Fourier.  So I started some serious refactoring of charts that impacts all screens, very necessary to support the Wave Packet screen. 

That refactor is on-going, and is likely to have introduced problems.   I thought that perhaps I could pick a stopping point, test, then publish the prototype for testing.  But there's a big problem with that - the code is still changing a lot.  While the first 2 screens are "feature complete", that doesn't mean that their code has stopped changing -- there is a lot of code shared by all screens, and I need to keep changing that code in order to proceed with the Wave Packet screen.  So I'm not sure how we do a dev test, when the code is changing significantly and frequently.  RC testing is also problematic - master will quickly diverge from the release branch, making it expensive to patch the release branch. 

Some options:

(1) Stabilize the current code base, then stop development on Fourier until the prototype is tested and published. This will result in several week's of delay for the public version, and doesn't make sense unless this test goes immediately to the head of the QA Pipeline.  The release branch will still be relatively easy to patch, because master will be effectively frozen. But the release branch will still be expensive to MR, because master and the release branch will quickly diverge when we resume development.  I'll lose momentum on development, but PhET-iO releases of my other sims have been doing that on a weekly basis. 

(2) Stabilize the current code base, have the team give it a high-priority workout in master, skip dev test, create a release branch immediately, cross our fingers, then RC test.  This will cause delay in the public version, but probably less delay than option (1).  This option does not avoid the problem of master and the release branch diverging, making it expensive to patch or MR the release branch.  If there are more than some simple fixes to be made in the release branch, this could turn into a nightmare.

(3) Skip the prototype and keep our eye on the public release. This is the option with lowest cost, that gets the public version released soonest. I don't know how important having a Fourier prototype is.

@arouinfar @kathy-phet Questions about the above options? Other ideas? How would you like to  proceed?

**Comment by kathy-phet** [comment]
I think we should wait for the code to settle down into a more stable place - then publish a prototype. This won't be the first sim used in the school year.

**Comment by arouinfar** [comment]
Let's wait for things to settle down and then we can re-assess the priority of a prototype.

**Comment by pixelzoom** [comment]
OK. I'll label this as deferred until we reach a better point to consider this.

**Comment by pixelzoom** [comment]
If we don't get aroun to doing this before publishing the public version...  Close this issue when the public version is published. And also close the dev-test issue phetsims/qa#673, if it's still open.

**Comment by pixelzoom** [comment]
The sim is now feature complete, and I'm going to start on cleanup and change requests. So I think it's highly unlikely that we can (or would) work on a prototype at this point. 

@arouinfar @kathy-phet can this issue be closed?

**Comment by arouinfar** [comment]
I don't think it makes sense to publish a prototype at this point, closing.
