### ISSUE TITLE
Sliders with interactive tick labels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#114]
In https://github.com/phetsims/fourier-making-waves/commit/6dd3f8f453ed00c3e6baf51169bf99e0be80d9e0, I added a new behavior to the Sliders that appear in the Wave Packet screen.  You can click on a tick label to set the value to that label.  I'm finding this very useful to quickly set sliders to common/reproducible values - for example, setting Wave Packet Center to 12π.

If you don't think this new behavior should be public, I can hide it behind a query parameter. Imo, it's not harmful, and could be useful (if discovered). And as I'm playing with it, I'm wondering why we never thought to make this a standard (optional?) feature of Slider.

@arouinfar thoughts?

**Comment by arouinfar** [comment]
@pixelzoom I love it! I have also found myself wanting to set a value to an exact value without requiring the thumb to snap to just the tick marks. The width sliders aren't good candidates for `constrainValue` due to their range.

I would be in favor of adding this feature to Slider. I think it would be helpful in other sims too.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sun/issues/712, I've requested adding interactive tick labels to Slider. In the meantime, the sim-specific implementation is fine, and added a TODO in the code that links to https://github.com/phetsims/sun/issues/712.

Looks like we're done here.  Closing.
