### ISSUE TITLE
Wave Packet screen review

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#122]
@arouinfar and @kathy-phet, the Wave Packet screen is now feature complete, including PhET-iO instrumentation. Please review in master. You can either create new issues for change requests, or add comments here and I'll decide whether to break out into a separate issue.

**Comment by pixelzoom** [comment]
@ariel too!

**Comment by ariel-phet** [comment]
@pixelzoom, here are my review comments (some for the Discrete Screen as well). These are all minor suggestions, and I think everything would be fine "as is" -- but here are some suggestions. (I review [dev.40](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.40/phet/fourier-making-waves_en_phet.html))

### Discrete Screen

1. I think the "sin" and "cos" font on this screen (and wave packet) under Graph controls could be bumped up. I think the font could be nearly the same sice as what you see in the "Function of" combo box. I am mainly thinking of a use where this sim is projected and those might be a bit small.

2. I think it might be good to have some sort of icon associated with the "Infinite Harmonics" checkbox, perhaps just a simple gray line that suggests "here is what you would say if you had infinite harmonics" -- basically just a bit more feedback to the user as to what that checkbox means.

3. I also think some sort of simple icon might be nice to associate with the Waveform combo box (perhaps a simple icon next to the Fourier Series title of the panel. My reasoning is that lets say you are on "Square" -- the moment you tweak a harmonic amplitude the waveform switches back to custom (as it should). But I think the user could still have the impression they are on a Square wave waveform. Having some kind of icon that disappears might help make the fact that you have switched back to custom more obvious.

4. If I am in "Function of space and time mode" and set all the amplitudes to zero, the period measurement tool still runs for every period. Not saying this is the wrong behavior, but it could potentially be confusing. Maybe do something like have the clock hand wind but have there be no color fill in this tool if that amplitude is zero? Suggesting that the period could be there but has no contribution currently?

### Wave Game

No specific feedback, I think if we implement @arouinfar suggestion regarding tweaking the challenges the matching precision will not be as much of a challenge. Otherwise, everything is looking good.

### Wave Packet

1. As noted above, increasing the font size of "sin" and "cos"

2. I would advocate for finding a way to get *k* rad/m label on one line. It just looks odd currently. I would advocate for just using "k" -- the units are in the control panel and I don't think you are losing much by removing the from the graph axis label in this case. 

3. Perhaps consider moving the default position of the "Lamda" green measuring tool. Currently if you don't move the tool from its default position and put on the "Width Indicators" they clash a bit. Not a big concern. Or perhaps easier would be to move the 
Width indicator vertically to the negative portion of the Sum graph (below the x-axis), since there is nothing special about having it on the positive side of the graph. Then this clash would be avoided in the default positions.

**Comment by pixelzoom** [comment]
@ariel-phet All good suggestions, thanks!  With the exception of the sin/cos font size, all of these suggestions require more discussion, so I've broken them out into separate issues.

**Comment by pixelzoom** [comment]
Raising priority to top.

**Comment by pixelzoom** [comment]
8/23/2021, Zoom design meeeting with @arouinfar @kathy-phet @pixelzoom 

Change requests are in these issues:

https://github.com/phetsims/fourier-making-waves/issues/156
https://github.com/phetsims/fourier-making-waves/issues/157
https://github.com/phetsims/fourier-making-waves/issues/158
https://github.com/phetsims/fourier-making-waves/issues/159
https://github.com/phetsims/fourier-making-waves/issues/118#issuecomment-904163871

Wave Packet screen review is done. Closing this issue.
