### ISSUE TITLE
Odd y-axis scale for Wave Packet Width = 4pi

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#128]
In this scenario, @kathy-phet reported its odd that y-axis scale is 0.99:

![screenshot_250](https://user-images.githubusercontent.com/3046552/129263563-b12ec989-b583-4df6-8abd-41b415a93733.png)

**Comment by pixelzoom** [comment]
The Java version behaves the same way - the max amplitude for width=4pi is noticeably smaller than the max amplitude for width=3pi.  It doesn't result in a y-axis scale change in the Java version, because the Java version handles y-axis scale differently.  But you can definitely see the change in the sum waveform.

I'm not sure if this is a bug in the model, or correct behavior.  @arouinfar what do you think?

**Comment by pixelzoom** [comment]
Java version screenshots, showing width=3pi vs 4pi:

![screenshot_253](https://user-images.githubusercontent.com/3046552/129267713-90b4e039-a91c-4862-baac-5b2878591f0d.png)

![screenshot_254](https://user-images.githubusercontent.com/3046552/129267724-599745f7-a3ba-4e18-a1c7-eb3973f0713b.png)

**Comment by pixelzoom** [comment]
Sorry, I didn't turn on "x-space envelope" in the above Java screenshots.  But I tested again, and I see similar behavior when "x-space envelope" is checked.

**Comment by arouinfar** [comment]
If the wave packet is centered at 10-14 pi, the max value looks fine to me. I only see an issue when it's centered at 9 or 15 pi (the min/max). Perhaps the max amplitude dips because there's more of the distribution's tail (which has very low amplitudes) is included in the sum? 

Would the changes to autoscale in #139 hide this issue @pixelzoom?

**Comment by pixelzoom** [comment]
> Perhaps the max amplitude dips because there's more of the distribution's tail (which has very low amplitudes) is included in the sum?

How do we confirm this hypothesis? And if that's the case, should we put something in Teacher Tips? 

> Would the changes to autoscale in #139 hide this issue @pixelzoom?

Those auto-scale changes are specific to the Discrete screen. Auto-scale for the Wave Packet screen is not changing.

**Comment by arouinfar** [comment]
> The Java version behaves the same way - the max amplitude for width=4pi is noticeably smaller than the max amplitude for width=3pi.

This is to be expected. The larger the standard deviation, the shorter the peak. Here's an example from the [Wiki page on Gaussians](https://en.wikipedia.org/wiki/Gaussian_function). 
![image](https://user-images.githubusercontent.com/8419308/130567563-04b71617-8c8b-41ec-a1c5-aa7b2ada6ff8.png)

I think the sim was behaving correctly, but given the changes in https://github.com/phetsims/fourier-making-waves/issues/159, this issue is now moot. Closing.
