### ISSUE TITLE
Infinite Harmonics curve should be gray

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fourier-making-waves#140]
Noticed while reviewing #135 in master

The Infinite Harmonics curve on the Discrete screen is black which obscures the Sum. Instead, the color should match the gray icon next to the checkbox.

![image](https://user-images.githubusercontent.com/8419308/129626880-8cfbef26-0925-4c46-bf41-d83c57af05c0.png)

**Comment by pixelzoom** [comment]
Yeah sorry, that got broken when I combined a bunch of different ProfileColorProperties into a single ProfileColorProperty. It's fixed in the above commit, screenshot below.   I won't bother you with reviewing, because it's so trivial/stupid.  Closing.


<img width="812" alt="screenshot_1186" src="https://user-images.githubusercontent.com/3046552/129627963-940a04e4-ecac-400a-a74e-ffd4a1c73feb.png">
