### ISSUE TITLE
Design for the "Expand sum" feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#20]
In the Java version, checking the "Expand sum..." checkbox opens this _**non-modal**_ dialog:

<img width="1020" alt="screenshot_717" src="https://user-images.githubusercontent.com/3046552/100688760-4dbbaa00-3340-11eb-80b6-849a1b25ea69.png">

Because this dialog is non-model, as you change things in the sim (amplitudes, number of harmonics, math form), the dialog updates. (It's not pretty, very jerky -- the dialog is recreated each time something changes.)

In JavaScript, we do not have non-modal dialogs. So we've tried to cram the expanded sum into the control panel:

<img width="323" alt="screenshot_711" src="https://user-images.githubusercontent.com/3046552/100687742-13e9a400-333e-11eb-90f6-142b07203039.png">

Lots of problems with this design: The control panel has to expand, pushing the sound controls to the bottom. As you change things in the sim (amplitudes, number of harmonics, math form), the control panel is constantly resizing.  The expanded sum takes up a lot of space. And there's no way to format it nicely.

So...  A proposal for a different design.  This proposal is based on the assumption that the student needs to see how the general form (shown above the Sum chart) is expanded, and they don't need to have that expanded form always visible.   Let's remove the "Expand sum" checkbox from the control panel, and add an "Info" button next to the general form that we want to see expanded, like this:

<img width="871" alt="screenshot_713" src="https://user-images.githubusercontent.com/3046552/100688133-d76a7800-333e-11eb-8841-aa0c90fd5510.png">

Pressing the "Info" button will open a _**modal**_ dialog that shows both the general form and the expanded sum.  Something like the example, but with nicer formatting. And note that you can still see the amplitude sliders (and value) behind this dialog.

<img width="865" alt="screenshot_715" src="https://user-images.githubusercontent.com/3046552/100688669-21a02900-3340-11eb-8e37-9d2e2c49d18d.png">

@arouinfar thoughts about this design? Suggestions for a different design?

**Comment by pixelzoom** [comment]
I've moved forward with the above proposal.  The expanded form is no longer shown in the control panel. It's now accessed via an Info button next to the general form equation, and is displayed in a dialog, screenshot below.  Lots of work still to be done on the formatting, but I'm going to defer that until I get input.

<img width="867" alt="screenshot_720" src="https://user-images.githubusercontent.com/3046552/100804172-a72be380-33e9-11eb-80e2-b8eba0e9de6e.png">

**Comment by pixelzoom** [comment]
12/3/2020 @arouinfar @kathy-phet @ariel-phet @pixelzoom 

Button and dialog are good.  Need to decide which button (and icon) to use, and how to format the dialog content.

**Comment by arouinfar** [comment]
I would change the title of the dialog to "Expanded Form" because that is the technical term for what it displays. It's a bit hard to describe how I'd pixel polish the equation, so here's a mockup of the ideal. Feel free to push back on anything that is unreasonable or unsupported.
![image](https://user-images.githubusercontent.com/8419308/101206081-daf64b80-362b-11eb-85c6-96bb3ea40fb9.png)
* Increase the line spacing so the equation doesn't look crowded 
* Left-align the `=` 
* Left -align terms that appear after the `=`
* Wrap the terms so the space under the `=` remains empty
* Wrap the lines so that the `+` isn't the first character of a new line

We decided to explore alternative icon because the info button `i` could be interpreted as the imaginary number *i*. I mocked up several options. The icons are generally intended to convey "expand" or "reveal". In case the icon isn't clear enough, we could try a text label instead.  My preference is option 1, though I would be fine with almost any of these options except for 4. @pixelzoom @ariel-phet which do you prefer?

| # | Screenshot |
| --- | --- |
| 1 | ![Screen Shot 2020-12-04 at 11 51 58 AM](https://user-images.githubusercontent.com/8419308/101202895-222e0d80-3627-11eb-9ec4-3764a190ca98.png) |
| 2 | ![Screen Shot 2020-12-04 at 11 48 37 AM](https://user-images.githubusercontent.com/8419308/101202803-ff9bf480-3626-11eb-91da-97112f716e35.png) |
| 3 | ![Screen Shot 2020-12-04 at 11 49 06 AM](https://user-images.githubusercontent.com/8419308/101202805-00348b00-3627-11eb-8551-1d64754d7456.png) |
| 4 | ![Screen Shot 2020-12-04 at 11 49 34 AM](https://user-images.githubusercontent.com/8419308/101202807-00cd2180-3627-11eb-9072-c8365b42f4ef.png) |
| 5 | ![Screen Shot 2020-12-04 at 11 49 52 AM](https://user-images.githubusercontent.com/8419308/101202810-0165b800-3627-11eb-97c0-5cdb7a5cfe1a.png) |
| 6 | ![Screen Shot 2020-12-04 at 11 50 31 AM](https://user-images.githubusercontent.com/8419308/101202811-01fe4e80-3627-11eb-9e59-668d93fd88da.png) |
| 7 | ![Screen Shot 2020-12-04 at 11 50 54 AM](https://user-images.githubusercontent.com/8419308/101202812-01fe4e80-3627-11eb-8212-e656636a167b.png) |

**Comment by pixelzoom** [comment]
Re equation format...  All of those requests are relatively easy _except_ the spacing between lines (leading).  I don't believe that RichText provides any support for leading, but I'll investigate.

Re button icon...  I'd like to avoid text and use an icon.   How about if we start with the eyeball and see how that feels?

**Comment by pixelzoom** [comment]
Re title... Easy to change to "Expanded Form".

Re equation format...  All of those requests are relatively easy _except_ the spacing between lines (leading).  I don't believe that RichText provides any support for leading, but I'll investigate.

Re button icon...  I'd like to avoid text and use an icon.   I don't think it's necessary that the icon communicates "this shows the expanded form", just that it's inviting and says "this shows something more that you might be interested in".  How about if we start with the eyeball and see how that feels?

**Comment by pixelzoom** [comment]
@arouinfar a question about the amplitude values... Should they be identical to the values shown above the amplitude sliders (i.e. always 2 decimal places -- e.g. 1.27, 1.00, 0.75, 0.40), or should we drop trailing zeros (e.g. 1.27, 1, 0.75, 0.4)?   Current behavior is the latter.

**Comment by pixelzoom** [comment]
>  I don't believe that RichText provides any support for leading, but I'll investigate.

Surprise, RichText does support leading!

**Comment by arouinfar** [comment]
>  question about the amplitude values... Should they be identical to the values shown above the amplitude sliders (i.e. always 2 decimal places -- e.g. 1.27, 1.00, 0.75, 0.40), or should we drop trailing zeros (e.g. 1.27, 1, 0.75, 0.4)? Current behavior is the latter (in HTML5 and Java versions)

I think dropping the trailing zeros looks cleaner in the equation, so let's stick with that.

> I'd like to avoid text and use an icon. I don't think it's vital that the icon communicates "this shows the expanded form", just that it's inviting and says "this shows something that you might be interested in". How about if we start with the eyeball and see how that feels?

I'd also prefer an icon over the text. The eyeball was my 2nd choice, and I think it communicates "show more" which is appropriate here. Let's move forward with the eyeball and we can get team feedback in the next design meeting.

**Comment by pixelzoom** [comment]
I was able to satisfy all of the change requests from https://github.com/phetsims/fourier-making-waves/issues/20#issuecomment-738976826, and this is ready for review.

I did need to reduce the number of terms-per-line from 4 to 3.  The worst-case (biggest dialog) is with 11 harmonics, all amplitudes at -1.27, function of 'space & time', math form = 'Wavelength & Period'.  It looks like this with 3 terms per line:

<img width="980" alt="screenshot_722" src="https://user-images.githubusercontent.com/3046552/101220680-53b4d200-3643-11eb-9b57-a6f00938b7be.png">

And here's a more typical case: 11 harmonics, preset = wave packet, function of 'space', math form = 'Mode'.

<img width="776" alt="screenshot_723" src="https://user-images.githubusercontent.com/3046552/101220751-76df8180-3643-11eb-8cb3-4783a83eb141.png">

Note that the font size difference in the above screenshots is caused by GitHub resizing the screenshots. In the sim, the font size is always the same.

**Comment by arouinfar** [comment]
The formatting looks great in master. The one pixel polish I have would be to increase the font size of "Expanded Form" so it feels more like a title. Let's try making it the same size as the equation. It's position and bold weight should be enough to make it feel like a title, even at the same font size.

Tagging for design meeting to review the icon choice for the button.

**Comment by pixelzoom** [comment]
Title font size increase to 18 (same as equations in the dialog):

<img width="930" alt="screenshot_762" src="https://user-images.githubusercontent.com/3046552/102415776-ff501180-3fb5-11eb-8ccc-4438830084ef.png">

**Comment by arouinfar** [comment]
Looks wonderful @pixelzoom!

**Comment by pixelzoom** [comment]
12/17/2020 @arouinfar @kathy-phet @ariel-phet @pixelzoom 

Dialog looks good. Everyone likes the eyeball button.
