### ISSUE TITLE
Add "Thanks" to credits.

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/fourier-making-waves#208]
So sorry I didn't think of this earlier, but today I was going to send the sim to STROBE leadership - as the funder, and checked and realized we hadn't added them to the "Thank you". 

This is what is in Wave Interference: 
Thanks To
This material is based upon work supported by the National Science Foundation under STROBE Grant No. DMR 1548924.

I will check to make sure this is the right credit. 

@pixelzoom - is this something that can be a maintenance release for this sim only? Again - apologies for the oversight.

**Comment by kathy-phet** [comment]
@arouinfar - I noticed that the in-sim credit and the sim-page credit for Wave Interference are different. Do you recall why?

**Comment by pixelzoom** [comment]
@arouinfar said:
> Also, I just noticed Wieman is misspelled, so we should fix that too.

Different issue, tracking in https://github.com/phetsims/fourier-making-waves/issues/210.

**Comment by pixelzoom** [comment]
I've added the "Thanks" section to master and 1.0 branches. Here's what it looks like:

<img width="717" alt="screenshot_1358" src="https://user-images.githubusercontent.com/3046552/137400208-44aa08fc-0915-4bd2-a023-793472e1573a.png">

Ready to publish.

**Comment by pixelzoom** [comment]
@arouinfar can you please update the "Thanks To" credits on the sim's web page? 

What it should say:

> We gratefully acknowledge support from STROBE NSF Science & Technology Center Grant DMR-1548924. Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation.

What it currently says:

<img width="1123" alt="screenshot_1359" src="https://user-images.githubusercontent.com/3046552/137400428-6f139f56-89f2-4afd-ac11-15c298e30184.png">

**Comment by pixelzoom** [comment]
> I'll also need to know whether you want this to go through an RC spot-check.

We're going to skip QA and publish 1.0.1 directly. 

<details>
<summary>Slack conversation</summary>

Chris Malley  3:52 PM
For the updates to Fourier credits, do you want the sim to go through an RC spot-check? Or are you comfortable skipping QA and publishing 1.0.1 ?   I would be comfortable skipping QA, because only the credits file has been changed.

Kathy Perkins  3:53 PM
I trust your judgement here. So if you are comfortable, sounds good to me.

Chris Malley  3:54 PM
Thanks. I’ll proceed with 1.0.1.  I’m also comfortable with this because we frequently revise the QA credits after the last RC, just before publication.

</details>

**Comment by pixelzoom** [comment]
Published in 1.0.1.  Closing.
