### ISSUE TITLE
Measurement tools are missing interactive highlights

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/fourier-making-waves#253]
**Test device**
MacBook Air M1 chip

**Operating System**
15.1.1

**Browser**
Safari 18.1.1

**Problem description**
For https://github.com/phetsims/qa/issues/1178, the measurement tools are missing interactive highlights. This includes:

- [ ] Discrete screen: measurement tools for Wavelength and Period 
- [ ] Wave Packet screen: measurement tools for k1 and λ1

**Steps to reproduce**
1. In the preferences menu, turn on interactive highlights
2. On the Discrete screen, select space & time under Graph Controls
3. Check the Wavelength and Period checkboxes
4. Hover over/move the measurement tools
5. Do something similar on the Wave Packet screen with k1 and  λ1

**Comment by pixelzoom** [comment]
It's unfortunate that adding a drag listener also means that programmers must remember to add the `InteractiveHighlighting` trait. That seems like something scenery could handle -- if interactive highlighting had been implemented via composition rather than as a trait. That said, the `InteractiveHighlighting` trait was missing for draggable tools, and I added it in the above commit, like so:

```diff
- export default class DiscreteMeasurementToolNode extends Node {
+ export default class DiscreteMeasurementToolNode extends InteractiveHighlighting( Node ) {

- export default class WavePacketMeasurementToolNode extends Node {
+ export default class WavePacketMeasurementToolNode extends InteractiveHighlighting( Node ) {
```

@Nancy-Salpepi please verify, close if OK.
