### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fourier-making-waves#259]
For https://github.com/phetsims/qa/issues/1178. Seen on Win 11 Chrome. First screenshot taken at start, and subsequent screenshots taken one minute apart during fuzzing.
There seems to be a noticeable memory leak in the dev test.
![memleak](https://github.com/user-attachments/assets/776f2af9-48c2-4296-afee-13b8b5a53308)

**Comment by pixelzoom** [comment]
Since this sim was converted to support dynamic locale, the most likely culprit here is a link to a LocalizedStringProperty that has not been cleaned up.  That is most typically a Text or RichText that needs to be disposed, but could be an explicit link, Multilink, or DerivedProperty.

**Comment by pixelzoom** [comment]
Because the `listenerLimit` query parameter is so useless, this issue has been brutal. I've had to manually inspect occurrence of things that link to LocalizedStringProperty.   It's like looking for a needle in a haystack.  ❗designates memory leaks that I found. I'm not confident that this is all of them.

### Text
- [x] LabeledExpandCollapseButton
- [x] SecondaryWaveformCheckbox
- [x] InfiniteHarmonicsCheckbox
- [x] ContinuousWaveformCheckbox
- [x] WaveformEnvelopeCheckbox
- [x] SumSymbolNode
- [x] DiscreteInfoDialog
- [x] PeriodCheckbox
- [x] WavelengthCheckbox
- [x] AmplitudeControlsSpinner
- [x] WaveGameInfoDialog
- [x] WaveGameLevelNode
- [x] WaveGameLevelSelectionNode
- [x] WavePacketInfoDialog
- [x] WidthIndicatorsCheckbox

### RichText
- [x] AmplitudeKeypadDialog
- [x] AmplitudeNumberDisplay
- [x] CalipersNode
- [x]  DomainChartNode
- [x] FMWComboBox
- [x] InteractiveAmplitudesChartNode
- [x] SeriesTypeRadioButtonGroup
- [x] SumSymbolNode
- [x] DiscreteInfoDialog
- [x] DiscreteSumEquationNode
- [x] ExpandedFormDialog
- [x] HarmonicsEquationNode
- [x] PeriodClockNode
- [x] WaveGameLevelNode
- [x] CenterControl
- [x] ComponentSpacingControl
- [x] ConjugateStandardDeviationControl
- [x] StandardDeviationControl
- [x] WavePacketInfoDialog
- [x] WavePacketMeasurementToolNode
- [x] ComponentSpacingToolNode
- [x] WavePacketLengthToolNode
- [x] WavePacketScreenView
- [x] WavePacketSumEquationNode
- [x] WidthIndicatorPlot
- [ ] ❗TickLabelUtils.createSymbolicTickLabel => TickLabelSet does not dispose Nodes

###  DerivedStringProperty
- [x] AmplitudeKeypadDialog
- [x] AmplitudeNumberDisplay
- [x] DomainChartNode
- [x] EquationMarkup
- [x] SumSymbolNode
- [x] PeriodClockNode
- [x] CaliperCheckbox
- [x] LengthToolCheckbox
- [x] WavePacketMeasurementToolNode
- [x] WavePacketLengthToolNode
- [x] WavePacketScreenView
- [x] WidthIndicatorPlot
- [ ] ❗TickLabelUtils.createSymbolicTickLabel => DerivedStringProperty is not disposed when RichText is disposed

### PatternStringProperty
- [x] AmplitudeKeypadDialog
- [x] GameLevel
- [x] WaveGameModel

**Comment by pixelzoom** [comment]
To check where this is at, I tested with https://phet-dev.colorado.edu/html/fourier-making-waves/1.1.0-dev.7/phet/fourier-making-waves_all_phet.html?fuzz.  Snapshots 1-10 are at 1-minute intervals. Snapshot 11 is 10 minutes after Snapshot 10.

No improvement at all here. In fact, this is much worse than what @KatieWoe reported. Either I did something to make it worse, or I picked up something from common code before I published /1.1.0-dev.7.  Ugh.

<img width="232" alt="screenshot_3628" src="https://github.com/user-attachments/assets/5ed9c19a-dc1e-4c6b-b230-c22b848ca451">

**Comment by pixelzoom** [comment]
https://phet-dev.colorado.edu/html/fourier-making-waves/1.1.0-dev.8/phet/fourier-making-waves_all_phet.html?fuzz was built with `grunt dev --brands=phet --minify.mangle=false`.

**Comment by pixelzoom** [comment]
https://phet-dev.colorado.edu/html/fourier-making-waves/1.1.0-dev.8/phet/fourier-making-waves_all_phet.html?fuzz was built with `grunt dev --brands=phet --minify.mangle=false`.  Same code, same test protocol.  Similar (bad) results shown below.

<img width="252" alt="screenshot_3629" src="https://github.com/user-attachments/assets/1056a91c-42c0-4010-b442-9034324968fb">

I tried comparing Snapshots 6 & 7, because there was a big increase there.  But I could not grok the comparison. Sorting by "# Delta", the top 10 are all very obfuscated:

<img width="801" alt="screenshot_3631" src="https://github.com/user-attachments/assets/98e9dcf3-4ff2-4855-a989-931a52ded46b">

**Comment by pixelzoom** [comment]
@jbphet and I looked at this, and he gave me a couple of good ideas for what state the sim should be in when taking heap snapshots.  And I'll probably do further debugging in the unbuilt version.

I'm also going to test with `"supportsInteractiveDescription": false,` in package.json, to see if these leaks are related to PDOM features.

**Comment by pixelzoom** [comment]
Running unbuilt in my local copy, http://localhost:8080/fourier-making-waves/fourier-making-waves_en.html?brand=phet&ea&debugger&fuzz, I am no longer seeing a memory leak. See snapshots below.  Snapshots 1-10 are at 1-minute intervals. Snapshot 11 is 10 minutes after Snapshot 10.  So heap size stabilizes at ~185 MB, and is still in that range after 20 minutes of fuzzing.

This test was done after fixing memory leaks for TickLabelSet over in https://github.com/phetsims/bamboo/issues/64.  I also made a simplification to how TickLabelSet removes unused labels from its cache, and that simplification involved removing a `Set` instance.  I don't know if it's related, but in https://github.com/phetsims/fourier-making-waves/issues/259#issuecomment-2518907926, I had identified `Set` as the largest "Size Delta" in heap comparisons. 

<img width="236" alt="screenshot_3632" src="https://github.com/user-attachments/assets/7d52c29b-d0ac-416d-a6c3-4d4f49c4f867">

**Comment by pixelzoom** [comment]
I backed out the memory leak fixes for TickLabelSet, then compared heap snaphots at startup and 20 minutes of fuzzing. See below. The memory leak did not return, and after 20 minutes of fuzzing, it's still in the ~185MB ballpark -- consistent with the test in https://github.com/phetsims/fourier-making-waves/issues/259#issuecomment-2521805802.  

So TickLabelSet was not the culprit.  Perhaps something got fixed in common code since the tests that I did yesterday? I'll ask in Slack#developer.

<img width="257" alt="screenshot_3633" src="https://github.com/user-attachments/assets/520a4296-34e3-49ed-be1a-d08304e59b33">

**Comment by pixelzoom** [comment]
> ... Perhaps something got fixed in common code since the tests that I did yesterday? I'll ask in Slack#developer.

In Slack#developer, @jessegreenberg replied:
> That seems really strange.  Do you have a dev version that always shows the leak?  And if so, does it leak in all browsers?  Maybe Chrome had something weird going on where it wasn't running GCs correctly.

Unfortunately, this issue has not been specific about Chrome version.  As noted above, 1.1.0-dev.5 through 1.1.0-dev.8 were all leaking badly.  So I retested 1.1.0-dev.7, noting that I'm using Chrome Version 131.0.6778.109 on macOS 15.1.1.   After 30 minutes of fuzzing, the heap size grew to ~500MB.   So it's not a problem with Chrome.

**Comment by pixelzoom** [comment]
https://phet-dev.colorado.edu/html/fourier-making-waves/1.1.0-dev.9/phet/fourier-making-waves_all_phet.html?fuzz was built with `grunt dev --brands=phet --minify.mangle=false`.   The number of snapshots is off because I forgot to clear snapshots. But the test protocol is the same: Snapshots 3-12 are at 1-minute intervals. Snapshot 13 is 10 minutes after Snapshot 12.  Like the unbuilt version in https://github.com/phetsims/fourier-making-waves/issues/259#issuecomment-2521805802, there is not indication of a memory leak.  Heap size stabilizes ~150MB.

<img width="226" alt="screenshot_3634" src="https://github.com/user-attachments/assets/3a8ff9cd-e3f1-4a60-8ccf-7394065f064a">

**Comment by pixelzoom** [comment]
Revisiting 1.1.0-dev.8, I used the test protocol that @jbphet suggested in https://github.com/phetsims/fourier-making-waves/issues/259#issuecomment-2521281417.  Digging down into the `Set` instances, which had the highest "Size Delta" in heap comparisons, I find `createLabel` in the Retainers, see below.  This is the function called by TickLabelSet to create tick labels, and it is what was fixed in https://github.com/phetsims/bamboo/issues/64.  So I'm going to conclude that (despite  https://github.com/phetsims/fourier-making-waves/issues/259#issuecomment-2521886793) TickLabelSet was indeed responsible for the memory leak.

<img width="540" alt="screenshot_3635" src="https://github.com/user-attachments/assets/739fbfd2-db12-493a-ac6f-066ad243624b">

**Comment by pixelzoom** [comment]
I've tested this so many times that I'm not going to ask @KatieWoe to test again, and I'll simply close the issue.  We'll be doing another memory test in RC, and that should suffice.

**Comment by pixelzoom** [comment]
Actually... I leave this open, to be verified in 1.1.0-rc.1.

**Comment by pixelzoom** [comment]
Please do a memory test for https://github.com/phetsims/qa/issues/1186.  If it looks OK, you can close this issue.

**Comment by KatieWoe** [comment]
Memory leak seems to be gone in rc.1
![goodmem](https://github.com/user-attachments/assets/6f429f77-442a-4785-b867-90dc15312065)
