### ISSUE TITLE
relocate y-axis zoom buttons for Sum graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#36]
In Discrete screen, move y-axis zoom button for Sum to bottom left.  Try to keep "Amplitude" y-axis label centered.

**Comment by pixelzoom** [comment]
I'm not wild about this, because I think the user will have a hard time finding these zoom buttons.  See below. 

<img width="954" alt="screenshot_772" src="https://user-images.githubusercontent.com/3046552/102560890-8f628980-4090-11eb-9aea-20cf6723fba5.png">

Another idea might be to group the y-axis label ("Amplitude") and the zoom buttons, then center that group on the y-axis.

@arouinfar your thoughts?

**Comment by pixelzoom** [comment]
Well... Bottom-left is starting to grow on me, the more I play with it.  It's certainly better than top-right.

**Comment by arouinfar** [comment]
I think the bottom-left alignment is vastly better than top-right. I think it's clear that the buttons are related the the y-axis, but users might overlook the buttons.

> Another idea might be to group the y-axis label ("Amplitude") and the zoom buttons, then center that group on the y-axis.

I think this would certainly make the buttons more visible, but it might not look as clean. If it's a relatively quick change, it might be nice to try out. Otherwise, we can wait and see what happens in interviews.

**Comment by pixelzoom** [comment]
It's not a quick change. So let's leave it as is, and check in interviews.

**Comment by pixelzoom** [comment]
@ariel-phet FYI because you mentioned in design meeting today. This is the issue about where to put the zoom button.

**Comment by pixelzoom** [comment]
See mockup below for another option for placement of the y-axis zoom buttons. To my eye, this is more visually pleasing. I did consider this layout previously, but ruled it out for a few reasons: 

(1) It is a much more complicated layout implementation. It has to properly handle the possibility of the y-axis label or zoom buttons being changed (text, visibility) via PhET-iO.  All of the charts in this sim use the same underlying implementation, where zoom buttons are optional, so that also complicates layout of the y-axis label.

(2) It looks a little odd to have some of the y-axis label vertically centered, and some not.

(3) When y-axis zoom buttons are present, it leaves less space for i18n of the y-axis label "Amplitudes".

(4) The zoom buttons are wider than the y-axis label.  So we'll have to check to see if tick marks start to overlap with the zoom buttons.  If that happens, we'll probably have to make the charts (all of them) a few pixels narrower.

I'd be OK with switching to this layout if you prefer it.

@arouinfar @ariel-phet thoughts?  And @ariel-phet did you brought up the issue of zoom button placement, but did you have any specific suggestions?

<img width="954" alt="yzoom" src="https://user-images.githubusercontent.com/3046552/129410482-6b7bf9e6-2c18-47e9-bbf6-18c3884e2695.png">

**Comment by pixelzoom** [comment]
As a reminder, here's a screenshot of what we did in the Java version. We grouped all of the zoom buttons together.  There are so many things that scream "bad UX" about this.... The look of the buttons is confusing, and so non-standard for zoom.  The placement of the buttons is bad: The y-axis zoom buttons are far away from the y-axis scale. The y-axis zoom buttons are closer to the x-axis scale than the x-axis zoom buttons are.  So our goal was to do something better in the HTML5 version. 

<img width="1024" alt="screenshot_1171" src="https://user-images.githubusercontent.com/3046552/129413481-8e78cf59-8ea7-4035-be72-054d5b658416.png">

**Comment by ariel-phet** [comment]
I certainly agree that the HTML5 version so far is a vast improvement, and in general, you are running up lots of tough space constraints. So the current placement is certainly a reasonable compromise.

I think if I were to try something different, it would be to actually put the y axis zoom controls *inside* the graph. I know that is a bit strange, but you will very rarely be covering anything particularly pedagogically important, since these are overall always repeating patterns.

Here would be a quick sketch, not saying this is perfect either, but I think it could work as an alternative if interviews show some usability issues. (Guessing this implementation would also have some trickiness since overlayed on the graph, might be a good thing to comment on from @pixelzoom in case we even consider such a direction). 

![fourier](https://user-images.githubusercontent.com/4051174/129416206-4d793635-e991-46d1-8956-30217a0ddb31.png)

**Comment by pixelzoom** [comment]
Putting y-axis zoom button inside the chart would be an easy change.  But should the x-axis zoom controls also be inside the chart?

**Comment by ariel-phet** [comment]
@pixelzoom I know it seems odd, but I think keeping outside the graph for the x-axis is preferable, you would tend to cover up a bit more information with the x-axis buttons inside the graph, and I think they work where they are. Since there is only one case where we have y-axis zoom controls, and they are rarely going to cover up much information, I think we could get away with it being a bit odd. It seems to me a reasonable trade off to make things a bit cleaner and less cramped, but have some oddness -- just my opinion. Again, I think the current placement could work, it just does not feel as proximal as I would like it.

**Comment by pixelzoom** [comment]
Yeah, there are other things about these charts that are odd.  For example, the x-axis is labeled on the axis, while the y-axis is labeled along the left (vertical) edge of the chart.  Usually we'd pick one of these labeling methods, and use it for both axes.  But it doesn't work here, given the space constraints.

So I'd be OK with putting the y-axis zoom buttons inside the chart.  And I think I like that better than where they are now.  

@arouinfar your opinion?

**Comment by pixelzoom** [comment]
Here's another idea for addressing the issue of where to put the y-zoom buttons.  Get rid of them! -- and the autoscale checkbox! I think we could find a better UI for addressing the issues around y-scale.  Let's discuss that in https://github.com/phetsims/fourier-making-waves/issues/139.

**Comment by arouinfar** [comment]
> Here's another idea for addressing the issue of where to put the y-zoom buttons. Get rid of them! 

@ariel-phet and I are both on-board with always autoscaling so we can close this issue and continue the discussion in #139.
