### ISSUE TITLE
polish the Discrete control panel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#38]
After the Discrete control panel has stabilized (in terms of what controls are in it, where they are located, what they are named,...)  we'll need to do some polishing (alignment of controls, spacing,...)  I'm not particularly happy with how it looks as of 1.0.0-dev.9:

<img width="294" alt="screenshot_777" src="https://user-images.githubusercontent.com/3046552/102666951-651ed380-4145-11eb-8198-57898eb120c3.png">

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/fourier-making-waves/issues/34#issuecomment-747887506, @kathy-phet provided some feedback on the control panel, as it was in 1.0.0-dev.8:

> Chiming in on other small aspects. I would add a bit more vertical spacing/padding in the right hand controls section. There is room to make the whole control taller so should be fine on space. I like the new Harmonics control, but I would put more padding between it and the Waveform (so we can increase the touch area more too of those smaller buttons). There seems to be ample room above the titles (e.g. Measurement Tools) but it feels a bit crowded vertically of the things below the titles. I like the info button.

**Comment by pixelzoom** [comment]
We might also consider vertically centering the control panel in available vertical space, so we don't have a huge negative space below the control panel.

Compare:

![screenshot_186](https://user-images.githubusercontent.com/3046552/102638482-c8dcd880-4114-11eb-925f-3b0b0dff5347.png)

![screenshot_188](https://user-images.githubusercontent.com/3046552/102638544-e316b680-4114-11eb-990a-e168bed4ba8b.png)

**Comment by pixelzoom** [comment]
Getting closer... In the above commit, I adjusted alignment of labels & controls, and increased spacing.  master now looks like this:

<img width="295" alt="screenshot_778" src="https://user-images.githubusercontent.com/3046552/102667032-9dbead00-4145-11eb-806c-3de69f229747.png">

**Comment by pixelzoom** [comment]
Instead of vertically centering the control panel, I added more vertical spacing between components. This will allow us to expand pointer areas more.  See screenshot below.  We can of course do more polishing, but I'm feeling pretty good about where this is at.  So over to @arouinfar for review of master.

<img width="997" alt="screenshot_808" src="https://user-images.githubusercontent.com/3046552/103713699-4197bd80-4f7a-11eb-9a80-8672e3ca9d95.png">

**Comment by arouinfar** [comment]
Thanks for iterating over this @pixelzoom. I think https://github.com/phetsims/fourier-making-waves/issues/38#issuecomment-754981405 looks really nice. The only thing that I think could use some tuning is the info button. 

Here are a few options:
![image](https://user-images.githubusercontent.com/8419308/103804623-ab15db80-500f-11eb-884c-8d422433d6cf.png)

Options 1 and 2 right-align the button with the horizontal divider lines, which I think cleans things up a bit. A downside of this placement is that the button might overlooked. It's certainly not the first thing we want users to interact with, but it contains some important information so we don't want users to overlook it entirely. We could make the button more attractive by giving the logo a different color. Option 2 uses the same color as the slider thumb, which I think adds some visual interest without being too bright.

Alternatively, Option 3 moves the button to the left so that it is in-line with the "Fourier Series" label. This placement may make the button *too* attractive. It may also imply that the dialog is about the Fourier Series specifically, when its purpose is more general. 

I'm personally leaning towards (1) or (2), and could go either way. What do you think @pixelzoom?

**Comment by pixelzoom** [comment]
Re button position... I definitely meant to right-align the button with the separators, so I've fixed that in the above commit. I don't like option 3 - this button is not specific to the "Fourier Series" section of the control panel, and moving the button close to that label implies that it's related. 

Re button color...  I have a very slight preference for the blue. It makes the button pop a little, but not too much. But I don't feel strongly about black vs blue.  @arouinfar ?

**Comment by arouinfar** [comment]
Thanks for your feedback @pixelzoom!

> Re button color... I have a very slight preference for the blue. It makes the button pop a little, but not too much.

Agreed! Let's go with the blue.

**Comment by pixelzoom** [comment]
Done! Fill is `rgb( 50, 145, 184 )`, same as SliderThumb.js.  Screenshot below.  

Closing.

<img width="267" alt="screenshot_809" src="https://user-images.githubusercontent.com/3046552/103830502-6b171e80-5038-11eb-9bc1-897485f55827.png">
