### ISSUE TITLE
"Harmonic" vs "Component" 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#78]
Related to https://github.com/phetsims/fourier-making-waves/issues/72 ...

We're not sure why the Discrete screen uses "Harmonic" while the Continuous screen users "Component".  We're considering changing to "Harmonic" in the Continuous screen.   I couldn't find anything in the Java design doc related to this, and that doc uses the 2 terms interchangeably when describing all screens.

@arouinfar will research whether there is a pedagogical reason for this difference.  @kathy-phet suggested asking Sam McKagan (Java version designer).

**Comment by arouinfar** [comment]
The terms "harmonic" and "component" aren't quite interchangeable.  In general, a component is a term in a Fourier series. On the Discrete Screen, the series presented is a harmonic series - each component in the series has a frequency that is an integer multiple of the fundamental, f<sub>1</sub>. However, on the Wave Packet screen, the terms displayed in the Components graph are not harmonics since the frequencies aren't integer multiples of the fundamental.

"Harmonics" supports the learning goals related to sound, so I would not change it to "Components" to match the Wave Packet screen. @pixelzoom let's continue to use "Harmonics" on the Discrete Screen and "Components" on the Wave Packet screen.

This distinction should be documented in the Teacher Tips, so I've opened #82.
