### ISSUE TITLE
Are values in the Continuous control panel labeled properly?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#79]
From https://github.com/phetsims/fourier-making-waves/issues/72#issuecomment-856223419, for the Continuous screen:

> I'm a little confused about how controls are labeled, and want to double check. For example, symbol "k" is documented in the Info dialog as "wave number". So is it accurate for Component Spacing to show "k1 = 1.5 rad/m"? If k1 is a wave number, how can it also be a value in rad/m?

This applies to all 4 sliders.

@arouinfar will investigate.

**Comment by arouinfar** [comment]
@pixelzoom I had to remind myself about the meaning of the wavenumber, k. It is the spatial frequency of a wave, measured in radians per unit distance. The wavenumber appears in the argument of the sine or cosine, such as Asin(kx),  so rad/m makes sense. 

The entry for k in the Symbols dialog should have units. Since the dialog is still up for review in #30, I'll add my comments there and close this issue.
