### ISSUE TITLE
Specify traversal order (pdomOrder) for the Wave Packet screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#84]
Related to https://github.com/phetsims/fourier-making-waves/issues/53.

Specify traversal order (pdomOrder) for the Wave Packet screen, document in https://docs.google.com/document/d/1wOdmPMD704u4OLl9avI9tl2jpTvsAAcZwMaNfnr0qSs/edit?pli=1#heading=h.qbkcpoz1vzlo.

I'll start by making it similar to the Discrete screen.

**Comment by pixelzoom** [comment]
@arouinfar I've implemented pdomOrder for the Wave Packet screen, so you may want to start by test-driving master.  Then let me know what you'd like to change.

**Comment by pixelzoom** [comment]
The measurement tools are not currently in the pdomOrder, because they have not been implemented. Unlike the Discrete screen, the measurement tools are always visible in this screen.  And where to put them in the pdomOrder is a little tricky.  The k<sub>1</sub> tool is used to measure the top chart.  The other tool is used to measure the Components or Sum chart.

**Comment by arouinfar** [comment]
@pixelzoom the current pdomOrder looks good to me. I added a section to the a11y doc for the Wave Packet screen. I still need to specify slider step sizes, but that's tracked in #83.

For the measurement tools, I see two options
(1) Group the tools together just after the control panel. This is consistent with the Discrete screen, though not completely analogous since these tools aren't ever turned off.
(2) Make each tool the first thing focused in its respective chart. Wave Number/Angular Frequency tool would be the first thing after the control panel, and the Wavelength/Period tool would be right before the Sum's ExpandCollapseButton.

I went with (1) in the design doc, but could be easily convinced to do (2).

**Comment by pixelzoom** [comment]
Thanks, I'll go with (1).  If we decide to change to (2), note that the Wavelength/Period tool is applicable to both the Components and Sum charts, so should probably be the first thing after the _Components'_ expand/collapse button, not the Sum's expand/collapse button.

**Comment by pixelzoom** [comment]
Duh. I just discovered that the width indicators are not interactive -- they appear on the charts to indicate the width, and are not movable.  So they will not be in the traversal order.

That means that this issue is ready for review by @arouinfar.

**Comment by pixelzoom** [comment]
Oh, wait... There are measurement tools, but they are always "on".  Fromhttps://github.com/phetsims/fourier-making-waves/issues/86:

> - [ ] measurement tools (k1, ω1, λ1, T1) with support for infinite components

So let's wait to review until those have been added.

**Comment by pixelzoom** [comment]
Measurement tools have been added to the traversal order.  As requested, they are after the control panel.

@arouinfar please review in master.

**Comment by arouinfar** [comment]
I like the Measurement Tools after the control panel. There have been some changes to the layout of this screen since I first specified the traversal order, but it's still looking good. I updated the a11y doc with the latest traversal order, so closing.
