### ISSUE TITLE
Show Answer button always disabled with alt input

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fourier-making-waves#87]
For #69 

When using the keyboard to play the game, the Show Answer button never becomes enabled, regardless of how many times the amplitudes are changed. Looks like the button's EnabledProperty isn't listening to keyboard events.

Steps to reproduce
1. Open Wave Game, any level
2. Tab to an amplitude slider and change the value
3. Repeat multiple times
4. Show Answer is always disabled

**Comment by pixelzoom** [comment]
We're currently enabling the 'Show Answer' button after the student has pressed on a slider N times. This is done via a PressListener on each slider.  Unfortunately "press" is not generalized for all forms of input, and this will require an additional alt-input-specific listener.

**Comment by pixelzoom** [comment]
Ugh... This is going to require big changes.  I can't add a KeyboardDragListener to the entire Amplitudes chart without making it focusable.  So I'll need to add to each AmplitudeSlider individually, via some new option(s).

**Comment by jessegreenberg** [comment]
Keyboard events bubble, another thing you could do is add an event listener like this to the WaveGameAmplitudesChartNode.
```js
this.addInputListener( {
  keyup: event => {
    if ( KeyboardUtils.isArrowKey( event.domEvent ) ) {
      this.numberOfPressesProperty.value++;
    }
  }
} );
```

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg.  I was hoping to do something that was specific to alt-input, not specific to keyboard, so that we don't have to revisit this in the future.  But maybe I'll do whatever is easiest for now.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg.  

I was hoping to do something that was specific to alt-input, not specific to keyboard, so that we don't have to revisit this in the future.

Calling KeyboardUtils.isArrowKey also relies on internal knowledge of the implementation of KeyboardDragListener, that is involves the arrow keys.  That's probably unlikely to change, but still feels unclean. 

But maybe I'll do whatever is easiest for now.

**Comment by jessegreenberg** [comment]
Yea, it is specific to keyboard. Another option would be to go through the `startDrag` option of Slider.js. This would require passing the callback to each Slider, but this is called for any form of alternative input, including keyboard events and `input` and `change` events from other devices.

Alternatively, instead of going through input would it work to use a DerivedProperty with dependencies on each Amplitude Property? Any change an amplitude would increments the number of changes? I guess you would need to exclude when amplitudes are changed externally like on reset all or PhET-iO.

**Comment by pixelzoom** [comment]
All good ideas, thanks.

**Comment by pixelzoom** [comment]
@jessegreenberg suggested. 
> Another option would be to go through the `startDrag` option of Slider.js. 

I investigated this, and it looked promising/straightforward,.  But unfortunately it does not get called when the user clicks on the slider track.  So it's not a reliable way to detect "an interactive with the Slider".

**Comment by jessegreenberg** [comment]
Would it be possible to pass the same `startDrag` to AmplitudeSlider's BarTrack? It looks like SliderTrack also takes a `startDrag` option and receives it when using the DefaultSliderTrack in Slider.js.

**Comment by pixelzoom** [comment]
Changes in https://github.com/phetsims/fourier-making-waves/issues/91 have made this a non-issue. The 'Show Answer' button is now enabled after the user has pressed the 'Check Answer' button 2x.

Closing.
