### ISSUE TITLE
Wave Game: Shift position of +1 Star

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fourier-making-waves#94]
For #69 

The placement of the +1 Star seems a bit off. It appears next to the Check Answer button, while logical, it looks unbalanced.
<img width="1439" alt="Screen Shot 2021-06-28 at 9 22 43 PM" src="https://user-images.githubusercontent.com/8419308/123733612-086d4580-d859-11eb-86fe-5ce6b8a5de89.png">

I would either center it horizontally
(1) in the layout bounds.
(2) over the graphs.

I don't have a strong preference between these options. @pixelzoom please pick the option that looks better to you.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.  I prefer horizontally centered on the charts, vertically centered on the layoutBounds.  That's were it was placed prior to the major changes that I made for #91.   I'll restore it to that position.

**Comment by pixelzoom** [comment]
Position fixed in the above commit, see screenshot below.  Closing.

<img width="999" alt="screenshot_1038" src="https://user-images.githubusercontent.com/3046552/124174767-fc0c0700-da69-11eb-8a7c-4bde2c7b8e07.png">

**Comment by pixelzoom** [comment]
Reopening.

I decided to also revisit the vertical alignment of the "+1 Star" and frowny face.  Rather than vertically centered on the layoutBounds, I think it looks better to vertically center on the Harmonics chart, as in the screenshots below.  

@arouinfar does this change look OK to you? If so, feel free to close. If not, it's easy to revert.

<img width="974" alt="screenshot_1040" src="https://user-images.githubusercontent.com/3046552/124175553-fa8f0e80-da6a-11eb-8285-ddcdbb108f29.png">
<img width="973" alt="screenshot_1039" src="https://user-images.githubusercontent.com/3046552/124175563-fd89ff00-da6a-11eb-9301-592d56a899d2.png">

**Comment by arouinfar** [comment]
Thanks @pixelzoom! I think the alignment in master looks really nice.
