### ISSUE TITLE
Make it easier to "match the pink waveform".

### ISSUE THREAD

**Issue by samreid** [phetsims/fourier-making-waves#97]
While testing the game, I was given a challenge to match a wave with 3 amplitudes.  I did this, but it was still marked wrong:

![image](https://user-images.githubusercontent.com/679486/123865849-a14ba180-d8e9-11eb-80ba-96ae0f49b57e.png)

Is the game too strict?

**Comment by pixelzoom** [comment]
Challenges are generated with amplitudes that are multiples of 0.5, which is the same interval as the amplitude sliders.   Solving a challenge means setting exact amplitude values, not "close enough".  In this case, you have not matched the pink wave. And if you had continued to tweak amplitudes, you probably would have discovered that you could get closer to the pink wave by tweaking the higher-order amplitude(s). 

If we want to make the game easier,  we could add a "close enough" tolerance.  But that tolerance would need to be a function of harmonic order, since 1 tolerance is probably not appropriate for all harmonics.  I'm not a fan of this, and recommend leaving it as is.

@arouinfar your opinion?

**Comment by arouinfar** [comment]
I've encountered similar situations when testing the sim -- the sum looks close but it's not an exact match. Generally, one or two sliders are off by 0.05 (a single step). In that case, troubleshooting is not particularly difficult. I don't think a "close enough" tolerance would be worth the added complexity. 

I've made a note to document the game requirements in the Teacher Tips. I'll also look out for student difficulties in interviews.

**Comment by pixelzoom** [comment]
8/12/21 design meeting:

@ariel-phet brought this up, reopening.

@samreid suggested comparing all points in answer and guess waveforms to determine if "close enough".

@arouinfar suggested changing challenge generation and sliders/keystep in Wave Game to use 0.1 increments. @kathy-phet likes this idea, we'll try this.

**Comment by pixelzoom** [comment]
Notes to self:

Game challenges and amplitude sliders current use `FMWConstants.AMPLITUDE_SLIDER_MOUSE_TOUCH_STEP`, value `0.05`.

Amplitude sliders already supports options for overriding this:

```js
      // {number} snap to this interval when using mouse/touch, unless the value is min or max
      mouseTouchStep: FMWConstants.AMPLITUDE_SLIDER_MOUSE_TOUCH_STEP,
...
      keyboardStep: FMWConstants.AMPLITUDE_SLIDER_MOUSE_TOUCH_STEP, // used by all alternative-input devices
```

AmplitudesChartNode will need similar option(s).  WaveGameAmplitudesChartNode subclass will overrides those options with value `0.1`.

**Comment by pixelzoom** [comment]
@arouinfar A question... If we're going to change the interval to 0.1 in Wave Game, should we also change the number of decimal places shown for amplitude to 0.1?  And restrict the keypad to 1 decimal place.  This would be relatively easy. And it seems odd to always show `0.N0` when moving the slider, and to allow entering 2 decimal places with the keypad.

**Comment by arouinfar** [comment]
>  If we're going to change the interval to 0.1 in Wave Game, should we also change the number of decimal places shown for amplitude to 1? And restrict the keypad to 1 decimal place? This would be relatively easy. 

Great question. That sounds reasonable to me, so let's do it.

**Comment by pixelzoom** [comment]
The Wave Game has been modified as requested:
* Amplitude sliders move in 0.1 intervals.
* Challenges have amplitude values in that are 0.1 intervals.
* NumberDisplays show values to 1 decimal place.
* Keypad allows you to enter values to 1 decimal place.

@arouinfar @ariel-phet please review in master and see if this adequately addresses the concerns.

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar -- this change definitely helps. I think once you get to 3 or more harmonics challenges still take quite a bit of "fiddling" to complete, but it seems that is a question for interviews to see whether students get frustrated or recognize that they were close if they get the answer wrong but are off by a couple of slider intervals.

**Comment by pixelzoom** [comment]
The pink waveform is currently plotted using a MUCH thicker `lineWidth` (4) that the your guess (1.5).  So your guess can look like it's entirely "inside" the plotted waveform, but not be "correct".  For example, see the screenshot below.  This could lead to incorrectly think that you've matched the pink waveform, or at least make it more difficult to see that your guess is not exactly correct. 

Perhaps we should tune these `lineWidth` values a bit? 

If we used the same `lineWidth` for both plots, then you will have matched the pink waveform when it's completely covered by your guess, and you can't see any pink.  The downside is that you won't be able to see the pink waveform when you've matched it. 

If we use a more similar lineWidth for both plots, you'll still be able to see the pink waveform behind a correct guess.  And there may be fewer cases where it looks like the guess is entirely "inside" the pink waveform.

@arouinfar @ariel-phet what do you think? Should we adjust `lineWidth` a bit?

Here are a couple of dev versions to try:

[1.0.0-dev.41]( https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.41/phet/fourier-making-waves_en_phet.html) - both plots with `lineWidth: 3`

[1.0.0-dev.42]( https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.42/phet/fourier-making-waves_en_phet.html) - pink `lineWidth: 3`, guess `lineWidth: 2`

<img width="1088" alt="screenshot_1182" src="https://user-images.githubusercontent.com/3046552/129585524-70efd4e3-06ff-4e96-b74b-f325371f87f6.png">

**Comment by pixelzoom** [comment]
FYI.. If you want to test this with specific challenges in the Wave Game, I've added a query parameter to help with that. `answer5` will initialize level 5 with a specific challenge. You must provide amplitude values for all 11 harmonics, including the zero values. Example: `?answer5=0,0.5,0,1,0,0,0,0,0,0,0`

**Comment by ariel-phet** [comment]
@pixelzoom good thought!

I played with dev.42 and think that is a nice compromise. I don't think making them the exact same width is as nice. It is pretty obvious with dev.42 that you are a bit off on a challenge, and feels very obvious when you truly match.

**Comment by arouinfar** [comment]
I much prefer the line widths in dev.42. It's nice to be able to see a faint pink glow behind the black curve. I think the combination of the updates listed in https://github.com/phetsims/fourier-making-waves/issues/97#issuecomment-898955393 and the line widths in dev.42 go a long way to address this issue. For levels 1 and 2, it is glaringly obvious when a solution is off by one tick. It gets a little trickier starting on level 3, but I think it's still fairly noticeable. 

The keyboard intervals need to be adjusted for the amplitude sliders. Currently, the shift and page up/down modifiers let users access values not divisible by 0.1. Let's update to:
- Arrow keys: 0.1
- Arrow + shift: 0.1 (same as regular step)
- Arrow + page up/down: 0.5

I think the most useful step size for solving the challenges is 0.1, so that should be the regular step size. In this situation, it is not productive to move in smaller step sizes, so we either should remove the shift modifier or just make it the same thing as the regular  step size (not sure what is better under the hood).

**Comment by pixelzoom** [comment]
In the above commits:

* answer (pink) plot has `lineWidth: 3`, guess (black) plot has `lineWidth: 2`
* Wave Game uses these option values for Amplitude sliders:

```js
      keyboardStep: 0.1,
      shiftKeyboardStep: 0.1,
      pageKeyboardStep: 0.5
```

@arouinfar please review in master. If it looks OK, you can close this issue.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom. I've interviewed on this sim twice so far. Neither had any trouble noticing when their solution was close but slightly off.
